spring:
  application:
    name: Hi-end-Systems-Test-Task
  datasource:
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/testtask"
  jpa:
    hibernate:
      ddl-auto: validate

testtask:
  jwt:
    secret: supersecretstringforjwtgeneration
    lifetime: 3600